# Default values for test-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: default

example:
  image:
    repository: "nginx"
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"
  container:
    name: os-test
  pv: os-test-pv
  pvc:
    name: os-test-pvc
    size: 10Gi
  commandStart: Today is 
  commandEnd:  and this is good.

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 750m
    memory: 256Mi
  requests:
    cpu: 500m
    memory: 128Mi

statefulSetName: test-stateful
serviceName: test-service
updateStrategy: RollingUpdate
statefulSetApp: test-app
storageClassName: slow